steps:
  - name: 'hashicorp/terraform:light'
    entrypoint: 'sh'
    args:
      - -c
      - |
          echo "Initializing Terraform..."
          terraform init

          echo "Importing Cloud SQL Instance..."
          terraform import google_sql_database_instance.odoo_db_instance projects/hippa-docai-demo/instances/odoo18-db-test

          echo "Importing Cloud SQL Database..."
          terraform import google_sql_database.odoo_db projects/hippa-docai-demo/instances/odoo18-db-test/databases/odoo18-test

          echo "Importing Cloud SQL User..."
          terraform import google_sql_user.odoo_db_user hippa-docai-demo/odoo18-db-test/odoo18

          echo "Importing Secret Manager Secret..."
          terraform import google_secret_manager_secret.odoo_db_password projects/hippa-docai-demo/secrets/odoo18-db-password

          echo "Importing Firewall Rule..."
          terraform import google_compute_firewall.allow_odoo_http projects/hippa-docai-demo/global/firewalls/allow-odoo-http-test

          echo "Importing Compute VM..."
          terraform import google_compute_instance.odoo_vm projects/hippa-docai-demo/zones/us-central1-a/instances/odoo18-vm-test

          echo "Applying Terraform configuration..."
          terraform apply -auto-approve

options:
  logging: CLOUD_LOGGING_ONLY