steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    dir: 'Odoo-Installation/Terraform/odoo18-terraform'
    args:
      - -c
      - |
          echo "Fetching password and writing terraform.auto.tfvars..."
          echo -n 'db_password        = "' > terraform.auto.tfvars
          gcloud secrets versions access latest --secret="odoo18-db-password" >> terraform.auto.tfvars
          echo '"' >> terraform.auto.tfvars

          echo 'project_id         = "hippa-docai-demo"'         >> terraform.auto.tfvars
          echo 'region             = "us-central1"'             >> terraform.auto.tfvars
          echo 'zone               = "us-central1-a"'           >> terraform.auto.tfvars
          echo 'vm_name            = "odoo18-vm-test"'          >> terraform.auto.tfvars
          echo 'db_instance_name   = "odoo18-db-test"'          >> terraform.auto.tfvars
          echo 'db_name            = "odoo18-test"'             >> terraform.auto.tfvars
          echo 'db_user_name       = "odoo18"'                  >> terraform.auto.tfvars
          echo 'secret_name        = "odoo18-db-password"'      >> terraform.auto.tfvars
          echo 'firewall_rule_name = "allow-odoo-http-test"'    >> terraform.auto.tfvars
          echo 'replica_location   = "us-central1"'             >> terraform.auto.tfvars
          echo 'github_connection  = "AvinashGitConnection"'    >> terraform.auto.tfvars
          echo 'github_owner       = "avinash2196"'             >> terraform.auto.tfvars
          echo 'github_repo        = "OddoDemo"'                >> terraform.auto.tfvars

  - name: 'hashicorp/terraform:light'
    entrypoint: sh
    dir: 'Odoo-Installation/Terraform/odoo18-terraform'
    args:
      - -c
      - |
          terraform init

          echo "Attempting to import pre-existing resources..."

          terraform import -allow-missing-config google_sql_database_instance.odoo_db_instance projects/hippa-docai-demo/instances/odoo18-db-test || true
          terraform import -allow-missing-config google_sql_database.odoo_db projects/hippa-docai-demo/instances/odoo18-db-test/databases/odoo18-test || true
          terraform import -allow-missing-config google_sql_user.odoo_db_user hippa-docai-demo/odoo18-db-test/odoo18 || true
          terraform import -allow-missing-config google_secret_manager_secret.odoo_db_password projects/hippa-docai-demo/secrets/odoo18-db-password || true
          terraform import -allow-missing-config google_secret_manager_secret_version.odoo_db_password_version projects/hippa-docai-demo/secrets/odoo18-db-password/versions/1 || true
          terraform import -allow-missing-config google_compute_firewall.allow_odoo_http projects/hippa-docai-demo/global/firewalls/allow-odoo-http-test || true

          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

options:
  logging: CLOUD_LOGGING_ONLY
